name: Check merchant-theme rebased on PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-merchant-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history to run git commands

      - name: Fetch merchant-theme branch
        run: git fetch origin merchant-theme

      - name: Check if merchant-theme is ancestor of PR branch
        run: |
          if git merge-base --is-ancestor origin/merchant-theme HEAD; then
            echo "merchant-theme is merged/rebased in this branch."
          else
            echo "::error::Branch must be rebased with merchant-theme."
            exit 1
          fi
