name: Ensure merchant-theme is merged

on:
  pull_request:
    branches: [main]

jobs:
  check-merchant-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to compare branches

      - name: Fetch merchant-theme
        run: git fetch origin merchant-theme

      - name: Ensure PR branch includes merchant-theme
        run: |
          if git merge-base --is-ancestor origin/merchant-theme HEAD; then
            echo "✅ merchant-theme is included"
          else
            echo "::error::❌ This PR is not rebased with merchant-theme"
            exit 1
          fi
