# This GitHub Actions workflow runs on Pull Requests targeting the 'main' branch.
# It verifies that the PR branch has been rebased or merged with the 'merchant-theme' branch.
# This ensures that the latest merchant changes from Shopify (in 'merchant-theme') are included
# in the feature or release branches before merging into 'main'.
#
# Steps:
# - Checks out the PR branch with full commit history.
# - Fetches the latest 'merchant-theme' branch for comparison.
# - Uses 'git merge-base' to check if 'merchant-theme' is an ancestor of the PR branch.
# - Fails the job with an error if the PR branch is not rebased/merged with 'merchant-theme',
#   enforcing that developers keep in sync with merchant changes.

name: Check merchant-theme rebased on PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-merchant-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history to run git commands

      - name: Fetch merchant-theme branch
        run: git fetch origin merchant-theme

      - name: Check if merchant-theme is ancestor of PR branch
        run: |
          if git merge-base --is-ancestor origin/merchant-theme HEAD; then
            echo "merchant-theme is merged/rebased in this branch."
          else
            echo "::error::Branch must be rebased with merchant-theme."
            exit 1
          fi
