# This GitHub Actions workflow deploys the Shopify theme automatically
# whenever changes are pushed to the 'main' branch.
#
# Workflow details:
# - Triggered on push events to the 'main' branch.
# - Checks out the latest code from the 'main' branch.
# - Sets up Node.js environment.
# - Installs Shopify CLI globally.
# - Runs the Shopify CLI command to push the theme to the Shopify store.
# - Uses secrets for theme ID, store domain, and CLI password for secure authentication.
#
# This automation ensures that approved and merged changes on 'main'
# are deployed immediately to the live Shopify store.

name: Deploy Theme to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        run: |
          shopify theme push \
            --json \
            --theme ${{ secrets.SHOPIFY_THEME_ID }} \
            --store ${{ secrets.SHOPIFY_STORE_DOMAIN }} \
            --password ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }} \
            --allow-live
